# Generated by Django 4.2.28 on 2026-02-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.ForeignKey(
                help_text="The organization (tenant) this record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                help_text="The organization (tenant) this record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "status"], name="idx_invoice_tenant_status"
            ),
        ),
    ]
