# Generated by Django 4.2.28 on 2026-02-25 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Domain event that triggers this workflow (e.g., 'invoice_paid').",
                        max_length=100,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible workflow configuration.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The organization (tenant) this record belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_workflow",
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("condition", "Condition"),
                            ("notification", "Notification"),
                            ("delay", "Delay"),
                            ("webhook", "Webhook"),
                        ],
                        default="action",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step-specific configuration (action params, conditions, etc.).",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The organization (tenant) this record belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_step",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The organization (tenant) this record belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_execution",
                "indexes": [
                    models.Index(
                        fields=["workflow", "status"], name="idx_exec_wf_status"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["tenant", "status"], name="idx_wf_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["trigger_event"], name="idx_wf_trigger"),
        ),
    ]
