# Generated by Django 4.2.28 on 2026-02-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                help_text="The organization (tenant) this record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_items",
                to="organizations.organization",
            ),
        ),
    ]
